import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
import PIL.Image as Image

connection = {
	"acinonyx-jubatus": "Cheetah",
	"aethia-cristatella": "Crested Auklet",
	"agalychnis-callidryas": "Tree Frog",
	"agkistrodon-contortrix": "Eastern Copperhead",
	"ailuropoda-melanoleuca": "Giant Panda",
	"ailurus-fulgens": "Red Panda",
	"alces-alces": "Moose",
	"anas-platyrhynchos": "Mallard",
	"ankylosaurus-magniventris": "Ankylosaurus",
	"apis-mellifera": "Western Honey Bee",
	"aptenodytes-forsteri": "Emperor Penguin",
	"aquila-chrysaetos": "Golden Eagle",
	"ara-macao": "Scarlet Macaw",
	"architeuthis-dux": "Giant Squid",
	"ardea-herodias": "Great Blue Heron",
	"balaenoptera-musculus": "Blue Whale",
	"betta-splendens": "Siamese Fighting Fish",
	"bison-bison": "American Bison",
	"bos-gaurus": "Gaur",
	"bos-taurus": "Domestic Cow",
	"bradypus-variegatus": "Brown-throated Three-toed Sloth",
	"branta-canadensis": "Canada Goose",
	"canis-lupus": "Wolf",
	"canis-lupus-familiaris": "Domestic Dog",
	"carcharodon-carcharias": "Great White Shark",
	"cardinalis-cardinalis": "Northern Cardinal",
	"cathartes-aura": "Turkey Vulture",
	"centrochelys-sulcata": "African Spurred Tortoise",
	"centruroides-vittatus": "Striped Bark Scorpion",
	"ceratitis-capitata": "Mediterranean Fruit Fly",
	"ceratotherium-simum": "White Rhino",
	"chelonia-mydas": "Green Sea Turtle",
	"chrysemys-picta": "Painted Turtle",
	"circus-hudsonius": "Northern Harrier",
	"codium-fragile": "Dead Man's Fingers",
	"coelacanthiformes": "Coelacanth",
	"colaptes-auratus": "Northern Flicker",
	"connochaetes-gnou": "Wildebeest",
	"correlophus-ciliatus": "Crested Giant Gecko",
	"crocodylus-niloticus": "Crocodile",
	"crotalus-atrox": "Western diamondback rattlesnake",
	"crotophaga-sulcirostris": "Groove-billed Ani",
	"cryptoprocta-ferox": "Fossa",
	"cyanocitta-cristata": "Blue Jay",
	"danaus-plexippus": "Monarch Butterfly",
	"dasypus-novemcinctus": "Nine-banded Armadillo",
	"delphinapterus-leucas": "Beluga",
	"dendrobatidae": "Poison Dart Frog",
	"dermochelys-coriacea": "Leatherback Sea Turtle",
	"desmodus-rotundus": "Vampire Bat",
	"diplodocus": "Diplodocus",
	"dugong-dugon": "Dugong",
	"eidolon-helvum": "Straw-coloured Fruit Bat",
	"enhydra-lutris": "Sea Otter",
	"enteroctopus-dofleini": "Giant Pacific octopus",
	"equus-caballus": "Horse",
	"equus-quagga": "Plains Zebra",
	"eudocimus-albus": "American white ibis",
	"eunectes-murinus": "Green Anaconda",
	"falco-peregrinus": "Peregrine Falcon",
	"felis-catus": "Cat",
	"formicidae": "Ant",
	"gallus-gallus-domesticus": "Chicken",
	"gavialis-gangeticus": "Gharial",
	"geococcyx-californianus": "Greater Roadrunner",
	"giraffa-camelopardalis": "Northern Giraffe",
	"gorilla-gorilla": "Gorilla",
	"haliaeetus-leucocephalus": "Bald Eagle",
	"hapalochlaena-maculosa": "Lesser Blue-ringed Octopus",
	"heloderma-suspectum": "Gila Monster",
	"heterocera": "Moth",
	"hippopotamus-amphibius": "Hippopotamus",
	"homo-sapiens": "Modern Humans",
	"hydrurga-leptonyx": "Leopard Seal",
	"icterus-galbula": "Baltimore Oriole",
	"icterus-gularis": "Altamira Oriole",
	"icterus-spurius": "Orchard Oriole",
	"iguana-iguana": "Green Iguana",
	"iguanodon-bernissartensis": "Iguanadon",
	"inia-geoffrensis": "Boto",
	"lampropeltis-triangulum": "Milk snake",
	"lemur-catta": "Ring-tailed Lemur",
	"lepus-americanus": "Snowshoe Hare",
	"loxodonta-africana": "African Bush Elephant",
	"macropus-giganteus": "Kangaroo",
	"malayopython-reticulatus": "Reticulated Python",
	"mammuthus-primigeniu": "Woolly Mammoth",
	"martes-americana": "American Marten",
	"megaptera-novaeangliae": "Humpback Whale",
	"melanerpes-carolinus": "Red-bellied Woodpecker",
	"mellisuga-helenae": "Bee Hummingbird",
	"mergus-serrator": "Red-breasted Merganser",
	"mimus-polyglottos": "Northern Mockingbird",
	"monodon-monoceros": "Narwhal",
	"musca-domestica": "Common House Fly",
	"odobenus-rosmarus": "Walrus",
	"okapia-johnstoni": "Okapi",
	"ophiophagus-hannah": "King Cobra",
	"orcinus-orca": "Killer Whale",
	"ornithorhynchus-anatinus": "Platypus",
	"ovis-aries": "Sheep",
	"ovis-canadensis": "Bighorn Sheep",
	"panthera-leo": "Lion",
	"panthera-onca": "Jaguar",
	"panthera-pardus": "Leopard",
	"panthera-tigris": "Tiger",
	"pantherophis-alleghaniensis": "Eastern Ratsnake",
	"pantherophis-guttatus": "Corn Snake",
	"papilio-glaucus": "Eastern Tiger Swallowtail",
	"passerina-ciris": "Painted Bunting",
	"pavo-cristatus": "Indian Peafowl",
	"periplaneta-americana": "American Cockroach",
	"phascolarctos-cinereus": "Koala",
	"phoebetria-fusca": "Sooty Albatross",
	"phoenicopterus-ruber": "American Flamingo",
	"phyllobates-terribilis": "Golden Poison Dart Frog",
	"physalia-physalis": "Portuguese Man o' War",
	"physeter-macrocephalus": "Sperm Whale",
	"poecile-atricapillus": "Black-capped Chickadee",
	"pongo-abelii": "Orangutan",
	"procyon-lotor": "Raccoon",
	"pteranodon-longiceps": "Pteranodon",
	"pterois-mombasae": "African Lionfish",
	"pterois-volitans": "Common Lionfish",
	"puma-concolor": "Cougar",
	"rattus-rattus": "Black Rat",
	"rusa-unicolor": "Sambar",
	"salmo-salar": "Salmon",
	"sciurus-carolinensis": "Eastern Gray Squirrel",
	"smilodon-populator": "Smilodon",
	"spheniscus-demersus": "African Penguin",
	"sphyrna-mokarran": "Great hammerhead shark",
	"spinosaurus-aegyptiacus": "Spinosaurus",
	"stegosaurus-stenops": "Stegosaurus",
	"struthio-camelus": "Common Ostrich",
	"tapirus": "Tapir",
	"tarsius-pumilus": "Pygmy Tarsier",
	"taurotragus-oryx": "Common Eland",
	"telmatobufo-bullocki": "Bullock Mountains False Toad",
	"thryothorus-ludovicianus": "Carolina Wren",
	"triceratops-horridus": "Triceratops",
	"trilobita": "Trilobites",
	"turdus-migratorius": "American Robin",
	"tursiops-truncatus": "Common Bottlenose Dolphin",
	"tyrannosaurus-rex": "T. Rex",
	"tyrannus-tyrannus": "Eastern Kingbird",
	"ursus-arctos-horribilis": "Grizzly Bear",
	"ursus-maritimus": "Polar Bear",
	"varanus-komodoensis": "Komodo Dragon",
	"vulpes-vulpes": "Red Fox",
	"vultur-gryphus": "Andean Condor"
}

endangered = {
    "acinonyx-jubatus": "Yes",
    "aethia-cristatella": "Yes",
    "agalychnis-callidryas": "Yes",
    "agkistrodon-contortrix": "No",
    "ailuropoda-melanoleuca": "Yes",
    "ailurus-fulgens": "Yes",
    "alces-alces": "No",
    "anas-platyrhynchos": "No",
    "ankylosaurus-magniventris": "No",
    "apis-mellifera": "No",
    "aptenodytes-forsteri": "Yes",
    "aquila-chrysaetos": "Yes",
    "ara-macao": "Yes",
    "architeuthis-dux": "Yes",
    "ardea-herodias": "No",
    "balaenoptera-musculus": "Yes",
    "betta-splendens": "No",
    "bison-bison": "No",
    "bos-gaurus": "Yes",
    "bos-taurus": "No",
    "bradypus-variegatus": "Yes",
    "branta-canadensis": "No",
    "canis-lupus": "Yes",
    "canis-lupus-familiaris": "No",
    "carcharodon-carcharias": "Yes",
    "cardinalis-cardinalis": "No",
    "cathartes-aura": "No",
    "centrochelys-sulcata": "Yes",
    "centruroides-vittatus": "No",
    "ceratitis-capitata": "No",
    "ceratotherium-simum": "Yes",
    "chelonia-mydas": "Yes",
    "chrysemys-picta": "No",
    "circus-hudsonius": "No",
    "codium-fragile": "No",
    "coelacanthiformes": "Yes",
    "colaptes-auratus": "No",
    "connochaetes-gnou": "No",
    "correlophus-ciliatus": "No",
    "crocodylus-niloticus": "Yes",
    "crotalus-atrox": "No",
    "crotophaga-sulcirostris": "No",
    "cryptoprocta-ferox": "Yes",
    "cyanocitta-cristata": "No",
    "danaus-plexippus": "No",
    "dasypus-novemcinctus": "No",
    "delphinapterus-leucas": "Yes",
    "dendrobatidae": "Yes",
    "dermochelys-coriacea": "Yes",
    "desmodus-rotundus": "No",
    "diplodocus": "No",
    "dugong-dugon": "Yes",
    "eidolon-helvum": "No",
    "enhydra-lutris": "Yes",
    "enteroctopus-dofleini": "No",
    "equus-caballus": "No",
    "equus-quagga": "Yes",
    "eudocimus-albus": "No",
    "eunectes-murinus": "No",
    "falco-peregrinus": "Yes",
    "felis-catus": "No",
    "formicidae": "No",
    "gallus-gallus-domesticus": "No",
    "gavialis-gangeticus": "Yes",
    "geococcyx-californianus": "No",
    "giraffa-camelopardalis": "Yes",
    "gorilla-gorilla": "Yes",
    "haliaeetus-leucocephalus": "No",
    "hapalochlaena-maculosa": "Yes",
    "heloderma-suspectum": "No",
    "heterocera": "No",
    "hippopotamus-amphibius": "Yes",
    "homo-sapiens": "No",
    "hydrurga-leptonyx": "No",
    "icterus-galbula": "No",
    "icterus-gularis": "No",
    "icterus-spurius": "No",
    "iguana-iguana": "Yes",
    "iguanodon-bernissartensis": "No",
    "inia-geoffrensis": "Yes",
    "lampropeltis-triangulum": "No",
    "lemur-catta": "Yes",
    "lepus-americanus": "No",
    "loxodonta-africana": "Yes",
    "macropus-giganteus": "No",
    "malayopython-reticulatus": "No",
    "mammuthus-primigeniu": "No",
    "martes-americana": "No",
    "megaptera-novaeangliae": "Yes",
    "melanerpes-carolinus": "No",
    "mellisuga-helenae": "No",
    "mergus-serrator": "No",
    "mimus-polyglottos": "No",
    "monodon-monoceros": "Yes",
    "musca-domestica": "No",
    "odobenus-rosmarus": "Yes",
    "okapia-johnstoni": "Yes",
    "ophiophagus-hannah": "Yes",
    "orcinus-orca": "Yes",
    "ornithorhynchus-anatinus": "No",
    "ovis-aries": "No",
    "ovis-canadensis": "Yes",
    "panthera-leo": "Yes",
    "panthera-onca": "Yes",
    "panthera-pardus": "Yes",
    "panthera-tigris": "Yes",
    "pantherophis-alleghaniensis": "No",
    "pantherophis-guttatus": "No",
    "papilio-glaucus": "No",
    "passerina-ciris": "No",
    "pavo-cristatus": "No",
    "periplaneta-americana": "No",
    "phascolarctos-cinereus": "Yes",
    "phoebetria-fusca": "No",
    "phoenicopterus-ruber": "Yes",
    "phyllobates-terribilis": "Yes",
    "physalia-physalis": "No",
    "physeter-macrocephalus": "Yes",
    "poecile-atricapillus": "No",
    "pongo-abelii": "Yes",
    "procyon-lotor": "No",
    "pteranodon-longiceps": "No",
    "pterois-mombasae": "No",
    "pterois-volitans": "No",
    "puma-concolor": "Yes",
    "rattus-rattus": "No",
    "rusa-unicolor": "No",
    "salmo-salar": "No",
    "sciurus-carolinensis": "No",
    "smilodon-populator": "No",
    "spheniscus-demersus": "Yes",
    "sphyrna-mokarran": "Yes",
    "spinosaurus-aegyptiacus": "No",
    "stegosaurus-stenops": "No",
    "struthio-camelus": "No",
    "tapirus": "Yes",
    "tarsius-pumilus": "No",
    "taurotragus-oryx": "Yes",
    "telmatobufo-bullocki": "No",
    "thryothorus-ludovicianus": "No",
    "triceratops-horridus": "No",
    "trilobita": "No",
    "turdus-migratorius": "No",
    "tursiops-truncatus": "Yes",
    "tyrannosaurus-rex": "No",
    "tyrannus-tyrannus": "No",
    "ursus-arctos-horribilis": "Yes",
    "ursus-maritimus": "Yes",
    "varanus-komodoensis": "Yes",
    "vulpes-vulpes": "No",
    "vultur-gryphus": "Yes"
}

classes = [
	"acinonyx-jubatus",
	"aethia-cristatella",
	"agalychnis-callidryas",
	"agkistrodon-contortrix",
	"ailuropoda-melanoleuca",
	"ailurus-fulgens",
	"alces-alces",
	"anas-platyrhynchos",
	"ankylosaurus-magniventris",
	"apis-mellifera",
	"aptenodytes-forsteri",
	"aquila-chrysaetos",
	"ara-macao",
	"architeuthis-dux",
	"ardea-herodias",
	"balaenoptera-musculus",
	"betta-splendens",
	"bison-bison",
	"bos-gaurus",
	"bos-taurus",
	"bradypus-variegatus",
	"branta-canadensis",
	"canis-lupus",
	"canis-lupus-familiaris",
	"carcharodon-carcharias",
	"cardinalis-cardinalis",
	"cathartes-aura",
	"centrochelys-sulcata",
	"centruroides-vittatus",
	"ceratitis-capitata",
	"ceratotherium-simum",
	"chelonia-mydas",
	"chrysemys-picta",
	"circus-hudsonius",
	"codium-fragile",
	"coelacanthiformes",
	"colaptes-auratus",
	"connochaetes-gnou",
	"correlophus-ciliatus",
	"crocodylus-niloticus",
	"crotalus-atrox",
	"crotophaga-sulcirostris",
	"cryptoprocta-ferox",
	"cyanocitta-cristata",
	"danaus-plexippus",
	"dasypus-novemcinctus",
	"delphinapterus-leucas",
	"dendrobatidae",
	"dermochelys-coriacea",
	"desmodus-rotundus",
	"diplodocus",
	"dugong-dugon",
	"eidolon-helvum",
	"enhydra-lutris",
	"enteroctopus-dofleini",
	"equus-caballus",
	"equus-quagga",
	"eudocimus-albus",
	"eunectes-murinus",
	"falco-peregrinus",
	"felis-catus",
	"formicidae",
	"gallus-gallus-domesticus",
	"gavialis-gangeticus",
	"geococcyx-californianus",
	"giraffa-camelopardalis",
	"gorilla-gorilla",
	"haliaeetus-leucocephalus",
	"hapalochlaena-maculosa",
	"heloderma-suspectum",
	"heterocera",
	"hippopotamus-amphibius",
	"homo-sapiens",
	"hydrurga-leptonyx",
	"icterus-galbula",
	"icterus-gularis",
	"icterus-spurius",
	"iguana-iguana",
	"iguanodon-bernissartensis",
	"inia-geoffrensis",
	"lampropeltis-triangulum",
	"lemur-catta",
	"lepus-americanus",
	"loxodonta-africana",
	"macropus-giganteus",
	"malayopython-reticulatus",
	"mammuthus-primigeniu",
	"martes-americana",
	"megaptera-novaeangliae",
	"melanerpes-carolinus",
	"mellisuga-helenae",
	"mergus-serrator",
	"mimus-polyglottos",
	"monodon-monoceros",
	"musca-domestica",
	"odobenus-rosmarus",
	"okapia-johnstoni",
	"ophiophagus-hannah",
	"orcinus-orca",
	"ornithorhynchus-anatinus",
	"ovis-aries",
	"ovis-canadensis",
	"panthera-leo",
	"panthera-onca",
	"panthera-pardus",
	"panthera-tigris",
	"pantherophis-alleghaniensis",
	"pantherophis-guttatus",
	"papilio-glaucus",
	"passerina-ciris",
	"pavo-cristatus",
	"periplaneta-americana",
	"phascolarctos-cinereus",
	"phoebetria-fusca",
	"phoenicopterus-ruber",
	"phyllobates-terribilis",
	"physalia-physalis",
	"physeter-macrocephalus",
	"poecile-atricapillus",
	"pongo-abelii",
	"procyon-lotor",
	"pteranodon-longiceps",
	"pterois-mombasae",
	"pterois-volitans",
	"puma-concolor",
	"rattus-rattus",
	"rusa-unicolor",
	"salmo-salar",
	"sciurus-carolinensis",
	"smilodon-populator",
	"spheniscus-demersus",
	"sphyrna-mokarran",
	"spinosaurus-aegyptiacus",
	"stegosaurus-stenops",
	"struthio-camelus",
	"tapirus",
	"tarsius-pumilus",
	"taurotragus-oryx",
	"telmatobufo-bullocki",
	"thryothorus-ludovicianus",
	"triceratops-horridus",
	"trilobita",
	"turdus-migratorius",
	"tursiops-truncatus",
	"tyrannosaurus-rex",
	"tyrannus-tyrannus",
	"ursus-arctos-horribilis",
	"ursus-maritimus",
	"varanus-komodoensis",
	"vulpes-vulpes",
	"vultur-gryphus"
]

def set_device():
	if torch.cuda.is_available():
		dev = "cuda:0"
	else:
		dev = "cpu"
	return torch.device(dev)

device = set_device()

checkpoint = torch.load('app/animal_image_checkpoint.pth.tar', weights_only=False)

# Classification

model = torch.load('app/animal_image.pth', weights_only=False)

mean = checkpoint['mean']
std = checkpoint['std']

image_transforms = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(torch.Tensor(mean), torch.Tensor(std))  # image = (image - mean) / std
])


def classify(image_path,model=model, image_transforms=image_transforms, classes=classes):
    model = model.eval()
    image = Image.open(image_path)
    image = image_transforms(image).float()
    image = image.unsqueeze(0)

    output = model(image)

    # Compute probabilities
    probabilities = F.softmax(output, dim=1)
    max_prob, predicted = torch.max(probabilities.data, 1)


    scientific_name = classes[predicted.item()]  # predicted.item() will return index
    common_name = connection[scientific_name]
    isEndangered = endangered[scientific_name]

    result = {
        "scientific_name": scientific_name,
        "common_name": common_name,
        "endangered": isEndangered,
        "probability": max_prob.item() * 100
    }
    return result
	


 